name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-bmi2"]
    runs-on: windows-2022

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2	
        with:	
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish_${{ matrix.arch }}.exe && strip fairy-stockfish_${{ matrix.arch }}.exe

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}.exe

      - name: make all
        if: ${{ matrix.arch == 'x86-64' }}
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=fairy-stockfish-all_${{ matrix.arch }}.exe largeboards=yes all=yes && strip fairy-stockfish-all_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: fairy-stockfish
          path: src/fairy-stockfish*.exe
